const codeInput = document.querySelector("#codeInput");
const fileInput = document.querySelector("#fileInput");
const fileList = document.querySelector("#fileList");
const analyzeBtn = document.querySelector("#analyzeBtn");
const sampleBtn = document.querySelector("#sampleBtn");
const copyBtn = document.querySelector("#copyBtn");
const signalsEl = document.querySelector("#signals");
const reportOutput = document.querySelector("#reportOutput");
const scoreRing = document.querySelector("#scoreRing");
const scoreValue = document.querySelector("#scoreValue");
const verdictTitle = document.querySelector("#verdictTitle");
const verdictText = document.querySelector("#verdictText");
const linesMetric = document.querySelector("#linesMetric");
const commentMetric = document.querySelector("#commentMetric");
const repeatMetric = document.querySelector("#repeatMetric");
const markerMetric = document.querySelector("#markerMetric");

let loadedFiles = [];
let lastReport = "";

const sampleCode = `// Utility functions generated for user management
export function validateUser(user) {
  if (!user) {
    return false;
  }

  if (!user.email) {
    return false;
  }

  if (!user.name) {
    return false;
  }

  // TODO: Add more validation logic here
  return true;
}

export function formatUser(user) {
  return {
    id: user.id,
    name: user.name,
    email: user.email,
    createdAt: user.createdAt,
  };
}

export function processUsers(users) {
  return users.map((user) => formatUser(user)).filter((user) => validateUser(user));
}`;

const markerPatterns = [
  /\bgenerated by\b/i,
  /\bas an ai\b/i,
  /\bchatgpt\b/i,
  /\bcopilot\b/i,
  /\bclaude\b/i,
  /\bplaceholder\b/i,
  /\badd more .* here\b/i,
  /\bexample implementation\b/i,
  /\bfor demonstration purposes\b/i,
  /\bTODO:?\s*(implement|add|replace|handle)/i,
];

const commentPattern = /^\s*(\/\/|#|\/\*|\*|<!--|--|;)/;
const identifierPattern = /\b[A-Za-z_$][A-Za-z0-9_$]{2,}\b/g;
const genericNames = new Set([
  "data",
  "item",
  "items",
  "result",
  "results",
  "temp",
  "value",
  "values",
  "input",
  "output",
  "helper",
  "utils",
  "manager",
  "handler",
  "processor",
  "response",
  "request",
]);

function clamp(value, min, max) {
  return Math.max(min, Math.min(max, value));
}

function normalizeLine(line) {
  return line
    .trim()
    .replace(/["'`][^"'`]*["'`]/g, "\"\"")
    .replace(/\b\d+(\.\d+)?\b/g, "0")
    .replace(/\s+/g, " ");
}

function getCode() {
  const uploaded = loadedFiles.map((file) => `\n/* FILE: ${file.name} */\n${file.content}`).join("\n");
  return `${codeInput.value}\n${uploaded}`.trim();
}

function calculateSignals(code) {
  const lines = code.split(/\r?\n/);
  const nonEmpty = lines.map((line) => line.trim()).filter(Boolean);
  const commentLines = nonEmpty.filter((line) => commentPattern.test(line));
  const normalized = nonEmpty.map(normalizeLine).filter((line) => line.length > 4);
  const duplicates = normalized.length - new Set(normalized).size;
  const markerMatches = markerPatterns.flatMap((pattern) => code.match(pattern) || []);
  const identifiers = code.match(identifierPattern) || [];
  const uniqueIdentifiers = new Set(identifiers.map((name) => name.toLowerCase()));
  const genericHits = identifiers.filter((name) => genericNames.has(name.toLowerCase()));
  const avgLineLength = nonEmpty.reduce((sum, line) => sum + line.length, 0) / Math.max(nonEmpty.length, 1);
  const longUniformLines = nonEmpty.filter((line) => line.length > 72 && Math.abs(line.length - avgLineLength) < 18);
  const nestedDepth = Math.max(...lines.map((line) => (line.match(/^\s*/) || [""])[0].length), 0);
  const testMentions = (code.match(/\b(test|spec|assert|expect|mock|fixture)\b/gi) || []).length;
  const errorMentions = (code.match(/\b(throw|catch|except|error|invalid|fallback)\b/gi) || []).length;
  const functionCount = (code.match(/\b(function|def|class|const|let|var|export|public|private)\b/g) || []).length;

  const repetitionRatio = duplicates / Math.max(normalized.length, 1);
  const commentRatio = commentLines.length / Math.max(nonEmpty.length, 1);
  const genericRatio = genericHits.length / Math.max(identifiers.length, 1);
  const identifierDiversity = uniqueIdentifiers.size / Math.max(identifiers.length, 1);
  const uniformityRatio = longUniformLines.length / Math.max(nonEmpty.length, 1);
  const testBalance = testMentions / Math.max(functionCount, 1);
  const errorBalance = errorMentions / Math.max(functionCount, 1);

  return [
    {
      id: "markers",
      label: "Provenance markers",
      detail:
        markerMatches.length === 0
          ? "No direct AI, generator, placeholder, or demo markers were found."
          : `${markerMatches.length} marker(s) found: ${[...new Set(markerMatches)].slice(0, 4).join(", ")}.`,
      score: clamp(markerMatches.length * 18, 0, 100),
      raw: markerMatches.length,
    },
    {
      id: "repetition",
      label: "Structural repetition",
      detail: `${Math.round(repetitionRatio * 100)}% of normalized non-empty lines repeat after strings and numbers are removed.`,
      score: clamp(repetitionRatio * 170, 0, 100),
      raw: repetitionRatio,
    },
    {
      id: "comments",
      label: "Comment texture",
      detail: `${Math.round(commentRatio * 100)}% comment lines. Very high ratios can indicate tutorial-style generated code.`,
      score: commentRatio > 0.28 ? clamp((commentRatio - 0.18) * 220, 0, 100) : 0,
      raw: commentRatio,
    },
    {
      id: "names",
      label: "Naming specificity",
      detail: `${Math.round(genericRatio * 100)}% of identifiers are generic; identifier diversity is ${Math.round(identifierDiversity * 100)}%.`,
      score: clamp(genericRatio * 140 + (0.22 - identifierDiversity) * 90, 0, 100),
      raw: genericRatio,
    },
    {
      id: "uniformity",
      label: "Line uniformity",
      detail: `${Math.round(uniformityRatio * 100)}% of meaningful lines have a similar long-form length.`,
      score: clamp(uniformityRatio * 125, 0, 100),
      raw: uniformityRatio,
    },
    {
      id: "resilience",
      label: "Edge-case evidence",
      detail: `Found ${errorMentions} error-handling term(s) and ${testMentions} test-related term(s) across roughly ${functionCount} declarations.`,
      score: clamp(52 - errorBalance * 28 - testBalance * 24, 0, 100),
      raw: { errorMentions, testMentions },
    },
    {
      id: "shape",
      label: "Complexity shape",
      detail: `Maximum indentation is ${nestedDepth} spaces. Flat code is not suspicious alone, but low contour can weaken provenance confidence.`,
      score: nonEmpty.length > 35 && nestedDepth < 8 ? 34 : 8,
      raw: nestedDepth,
    },
  ];
}

function scoreColor(score) {
  if (score >= 68) return "var(--red)";
  if (score >= 40) return "var(--gold)";
  return "var(--green)";
}

function verdictFor(score) {
  if (score >= 68) {
    return {
      title: "High AI-coded risk",
      text:
        "Several signals resemble generated or lightly reviewed code. Treat this as a triage result and inspect the highlighted evidence before making a call.",
    };
  }
  if (score >= 40) {
    return {
      title: "Mixed origin signals",
      text:
        "The sample has some generated-code traits, but not enough to call it AI-coded. Ask for commit history, tests, and rationale around the suspicious sections.",
    };
  }
  return {
    title: "Low AI-coded risk",
    text:
      "The sample does not show strong generated-code signals. This is not proof of human authorship, but the evidence looks comparatively natural.",
  };
}

function buildReport(code, signals, score) {
  const verdict = verdictFor(score);
  const topSignals = [...signals].sort((a, b) => b.score - a.score).slice(0, 4);

  return [
    "CODE ORIGIN VERIFICATION REPORT",
    "================================",
    `Verdict: ${verdict.title}`,
    `Risk score: ${score}/100`,
    `Lines analyzed: ${code.split(/\r?\n/).filter(Boolean).length}`,
    "",
    "Important caveat:",
    "This tool detects provenance signals, not authorship. A careful human can write generic code; an AI-assisted change can be excellent after review.",
    "",
    "Strongest evidence:",
    ...topSignals.map((signal) => `- ${signal.label}: ${signal.detail} Score ${signal.score}/100`),
    "",
    "Suggested follow-up:",
    "- Ask the author to explain design choices and tradeoffs.",
    "- Compare against commit history and surrounding project style.",
    "- Check tests, failure modes, and issue-specific constraints.",
    "- Review any repeated blocks or placeholder language manually.",
  ].join("\n");
}

function renderResults(code) {
  if (!code) {
    verdictTitle.textContent = "Awaiting code";
    verdictText.textContent = "Add code to generate a grounded audit with specific evidence.";
    return;
  }

  const lines = code.split(/\r?\n/);
  const signals = calculateSignals(code);
  const score = Math.round(signals.reduce((sum, signal) => sum + signal.score, 0) / signals.length);
  const verdict = verdictFor(score);
  const commentRatio = signals.find((signal) => signal.id === "comments").raw;
  const repeatRatio = signals.find((signal) => signal.id === "repetition").raw;
  const markers = signals.find((signal) => signal.id === "markers").raw;

  scoreRing.style.setProperty("--score", score);
  scoreRing.style.setProperty("--ring-color", scoreColor(score));
  scoreValue.textContent = score;
  verdictTitle.textContent = verdict.title;
  verdictText.textContent = verdict.text;
  linesMetric.textContent = lines.filter((line) => line.trim()).length;
  commentMetric.textContent = `${Math.round(commentRatio * 100)}%`;
  repeatMetric.textContent = `${Math.round(repeatRatio * 100)}%`;
  markerMetric.textContent = markers;

  signalsEl.innerHTML = signals
    .map(
      (signal) => `
        <article class="signal">
          <div>
            <strong>${signal.label}</strong>
            <span>${signal.detail}</span>
          </div>
          <div class="signal-score" style="background:${scoreColor(signal.score)}">${signal.score}</div>
        </article>
      `,
    )
    .join("");

  lastReport = buildReport(code, signals, score);
  reportOutput.textContent = lastReport;
}

async function handleFiles(files) {
  const readableFiles = [...files].filter((file) => file.size < 600000);
  loadedFiles = await Promise.all(
    readableFiles.map(async (file) => ({
      name: file.name,
      content: await file.text(),
    })),
  );

  fileList.textContent =
    loadedFiles.length === 0
      ? "No files loaded"
      : `${loadedFiles.length} file(s): ${loadedFiles.map((file) => file.name).join(", ")}`;
}

document.querySelectorAll(".tab").forEach((tab) => {
  tab.addEventListener("click", () => {
    document.querySelectorAll(".tab").forEach((item) => item.classList.remove("is-active"));
    document.querySelectorAll(".view").forEach((view) => view.classList.remove("is-active"));
    tab.classList.add("is-active");
    document.querySelector(`#${tab.dataset.view}View`).classList.add("is-active");
  });
});

fileInput.addEventListener("change", (event) => handleFiles(event.target.files));

analyzeBtn.addEventListener("click", () => renderResults(getCode()));

sampleBtn.addEventListener("click", () => {
  codeInput.value = sampleCode;
  renderResults(getCode());
});

copyBtn.addEventListener("click", async () => {
  if (!lastReport) return;
  await navigator.clipboard.writeText(lastReport);
  copyBtn.textContent = "Copied";
  setTimeout(() => {
    copyBtn.textContent = "Copy report";
  }, 1200);
});

renderResults("");
